# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 19 * * *'

jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task1
      run: npm run task1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 

  task2:
    runs-on: ubuntu-latest
    needs: [task1]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task2
      run: npm run task2
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  task3:
    runs-on: ubuntu-latest
    needs: [task1,task2]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task3
      run: npm run task3
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
  task4:
    runs-on: ubuntu-latest
    needs: [task1,task2,task3]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task4
      run: npm run task4
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 

  task5:
    runs-on: ubuntu-latest
    needs: [task1,task2,task3,task4]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task5
      run: npm run task5
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  task6:
    runs-on: ubuntu-latest
    needs: [task1,task2,task3,task4,task5]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run task6
      id: task6
      run: npm run task6
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.task6.outputs.version }}
        release_name: Release ${{ steps.task6.outputs.version }}
        body: ${{ steps.task6.outputs.version }}
        draft: false
        prerelease: false  
