# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: GIT_CONFIG
      run: git config pull.rebase false
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - name: Run Daily Task
      id: daily
      run: npm run daily
    - name: Test
      run: npm test
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - name: Publish to NPM
      run: npm publish
      env:
          NODE_AUTH_TOKEN: ${{secrets.npm_publish}}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.daily.outputs.version }}
        release_name: Release ${{ steps.daily.outputs.version }}
        body: ${{ steps.daily.outputs.version }}
        draft: false
        prerelease: false
