# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 16 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Run Daily Task
      run: npm run task1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.task6.outputs.version }}
        release_name: Release ${{ steps.task6.outputs.version }}
        body: ${{ steps.task6.outputs.version }}
        draft: false
        prerelease: false  
  
