# This is a basic workflow to help you get started with Actions

name: Update Data CI 2

on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - name: Run Update Data 2
      id: full2
      run: npm run full2
    - name: Test
      run: npm test
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
